# -*- coding: utf-8 -*-
"""paraphrase

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S411dyyvgzfYaoGNWChx0nZzhqKiWixf
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("yuniv/KoSST")

model = AutoModelForSeq2SeqLM.from_pretrained("yuniv/KoSST")

import torch

def paraphrasing(text):
    tokenized_text = tokenizer(text, return_tensors='pt', truncation=True)
    with torch.no_grad():
        outputs = model.generate(
            tokenized_text['input_ids'],
            do_sample = True,
            eos_token_id = tokenizer.eos_token_id,
            max_length = 512,
            top_p = 0.7,
            top_k = 20,
            # num_beams=10,
            num_return_sequences = 1,
            no_repeat_ngram_size = 2,
            early_stopping = True
        )
        return tokenizer.decode(outputs[0], skip_special_tokens = True)

print("*"*80)
print("paraphrasing(\"<s>\"+[바꿀 문장]+\"</s>\") 코드를 작성해 직접 실행해볼 수 있습니다")
sentence = input("반말(비격식체)로 문장을 작성해보세요: ")
print("*"*80)

print("바뀐 문장:",paraphrasing("<s>"+sentence+"</s>"))
print("노트북 환경에서 실행하는 경우, 실행 버튼을 여러 번 눌러 여러 문장을 확인합니다")
